---
title: "EDA"
output: html_document
date: "2023-07-19"
---


```{r}
library(quantmod)
library(tidyquant)
library(tidyverse)
library(readr)
library(pastecs)
library(PerformanceAnalytics)
library(lubridate)
library(taskscheduleR)
library(RPostgreSQL)
library(reshape2)
library(priceR)
library(psych)
library(PMwR)
library(forecast)
```

```{r}
con <- DBI::dbConnect(RPostgres::Postgres()
                      , host='localhost'
                      , port='5432'
                      , dbname= 'postgres'
                      , user='postgres'
                      , password="Chui1234!")
```

```{r}
up_ratio <- 0.2
down_ratio <- -0.2

cl <- dbGetQuery(con, "SELECT * from cl;")
symbol_list <- cl %>% 
  distinct(symbol)

stock_all <- data.frame(matrix(ncol = 6, nrow = 0))
n <- length(symbol_list$symbol)
pb <- txtProgressBar(min = 0, max = n, style=3)

for (i in 1:length(symbol_list$symbol))
{
  tryit <- try(
    {
      stock <- cl %>%
        filter(symbol == symbol_list[i,])
      s <- streaks(as.xts(stock[,c(2,6)]), up = up_ratio, down = down_ratio)
      s <- data.frame(symbol = symbol_list[i,], s)
      s$duration <- s$end - s$start
      stock_all <- rbind(stock_all, s)
}
  )
  if(inherits(tryit, "try-error")){
    i <- i+1
  } 
    setTxtProgressBar(pb, i)
}
```

```{r}
stock_anomaly <- data.frame(matrix(ncol = 6, nrow = 0))
for (i in 1:length(symbol_list$symbol))
{
  tryit <- try(
    {
      stock <- cl %>%
        filter(symbol == symbol_list[i,])
      stock_xts <- as.xts(stock[,c(2,6)])
      #stock_xts <- na.omit(diff(stock_xts,1))
      anomaly_index <- tsoutliers(stock_xts)$index
      replacements <- tsoutliers(stock_xts)$replacements
      stock_xts$anomaly <- "no"
      stock_xts[anomaly_index,2] <- "yes"
      stock_xts$replacement <- "no"
  # identify anomaly 
  stock[anomaly_index,3]<- replacements # replace anomaly
  #stock <- merge(stock, Stock)
  stock_anomaly <- rbind(stock_anomaly, stock)
    }
  )
  if(inherits(tryit, "try-error")){
    i <- i+1
  } 
    setTxtProgressBar(pb, i)
}
```

####
---interest rate---
```{r}
library(readr)
REAINTRATREARAT10Y <- tq_get("REAINTRATREARAT10Y", get = "economic.data", complete_cases = TRUE)
col_types = cols(date = col_date(format = "%d/%m/%Y"))
down_ratio <- -0.5
up_ratio <- 0.5
s <- streaks(as.xts(REAINTRATREARAT10Y[,c(2,3)]), up = up_ratio, down = down_ratio)
write.csv(s, "s.csv")
```

```{r}
down_ratio <- -0.3
up_ratio <- 0.3
from_date <- "1980-01-01"
gspc <- getSymbols("^GSPC", from = from_date, to = Sys.Date() -2)
s <- streaks(GSPC[,4], up = up_ratio, down = down_ratio)
write.csv(GSPC, "gspc.csv")
```

```{r}
dbRemoveTable(con, "stock_return")
stock_all$duration <- as.numeric(stock_all$duration)
dbWriteTable(con, "stock_return", stock_all)
```

